### ISSUE TITLE
Make a default action?

### ISSUE THREAD

**Issue by millisami** [erikhuda/thor#167]
I just have only one action which takes only one argument in my library. 

``` ruby
module CMG
  class CLI < Thor
    include Thor::Actions

    desc "vanmuji", "does something"
    def vanmuji(linga=nil)
      puts "u n me happy: #{linga}"
    end
  end
end
```

Thor gives me the way to call it as:

cmg hrocess aloovantakovi.txt

But I'ld like to call it as:

  `cmg aloovantakovi.txt`

and I like to invoke the same `vanmuji` method with the `aloovantakovi.txt` as an argument.

**Comment by gtmax** [comment]
Can work around this using
```
ARGV.unshift('vanmuji') if ARGV[0] != 'vanmuji'
```

before doing `CLI.start`
