### ISSUE TITLE
required class option makes help command less useful

### ISSUE THREAD

**Issue by b-dean** [erikhuda/thor#363]
When a `Thor` class has required class options, it makes the `help` command also require them. This means that the user can't run `cli help COMMAND` to get help on that command because the required options are not provided. Here's an example:

```ruby
require 'thor'
class Example < Thor
  class_option :username, :desc => 'Some username', :required => true
  class_option :password, :desc => 'Some password', :required => true

  desc 'do_something', 'Do something'
  def do_something
    ExternalSystem.new(options[:username], options[:password]).do_something
  end

  desc 'something_else', 'Some other thing'
  def something_else
    ExternalSystem.new(options[:username], options[:password]).something_else
  end
end

Example.start(%w{help do_something})
```

I would expect that to give some help for the `do_something` command so the user knows what options are needed. Instead I just get:

    No value provided for required options '--username', '--password'

Is there some way to make these class options not apply to the `help` command?

**Comment by kaelumania** [comment]
whats the status of this issue?

**Comment by b-dean** [comment]
I don't know. As you can see #462 has been sitting there for a while.

**Comment by rspencer01** [comment]
Bug is still biting.  Please fix!

**Comment by sferik** [comment]
I just merged #462. I’ll see if I can put a release together soon.

**Comment by sferik** [comment]
In the mean time, can everyone please verify that this problem is fixed in `master`?

**Comment by nishidy** [comment]
I tried the master and it just worked with class_option and required:true together but failed on 0.19.1 with Thor::RequiredArgumentMissingError.

**Comment by xam7247** [comment]
Does this work for anyone ? I am still facing this issue, even when I make method_options required. Thor v0.19.1

**Comment by omgreenfield** [comment]
'Twould be great if, when we close a ticket like this, we provide an example of it working instead of hoping people can figure out by inspecting the code. I can't get this feature to work
