### ISSUE TITLE
Heroku style commands

### ISSUE THREAD

**Issue by jacobbednarz** [erikhuda/thor#365]
Hey,
Using thor at the moment as a CLI tool for an API and one of the things I would like to do is create Heroku style commands. For anyone that is unsure what I a mean, here is an example.

```
$ myclitool

Commands:
  myclitool servers:list
  myclitool servers:add
  myclitool servers:status
```

instead of thor's default

```
$ myclitool

Commands:
  myclitool servers list
  myclitool servers add
  myclitool servers status
```

I have altered the `banner` method to output it correctly however it just doesn't accept it the subcommands.

``` ruby
def self.banner(task, task_help = false, subcommand = false)
  subcommand_banner = to_s.split(/::/).map{|s| s.downcase}[2..-1]
  subcommand_banner = if subcommand_banner.size > 0
                        subcommand_banner.join(':')
                      else
                        nil
                      end

  task = (task_help ? task.formatted_usage(self, false, subcommand) : task.name)
  banner_base + " " + [subcommand_banner, task].compact.join(":")
end
```

Can anyone point me in the right direction with this one?

**Comment by kaelumania** [comment]
@jacobbednarz what was the solution?

**Comment by jacobbednarz** [comment]
It's been a little while since I done it however I believe it was contained in these [two](https://github.com/jacobbednarz/acquia-toolbelt/commit/4756572d6f2a275ef868ea13b3ea10b674389920) [commits](https://github.com/jacobbednarz/acquia-toolbelt/commit/68ddbe58acc44a3cbbc04f13d089c05327c70592).

Checkout the full project at https://github.com/jacobbednarz/acquia-toolbelt if you want to go through the code.
