### ISSUE TITLE
long_desc: force keeping spaces and not break lines

### ISSUE THREAD

**Issue by mdesantis** [erikhuda/thor#398]
Hello,

I have a `long_desc` method like this:

``` ruby
long_desc <<-LONGDESC.gsub("\n", "\x5")
  Examples:

  bin/ruby-rails-documentations                             \\
    generate ~/ruby-rails-documentations                    \\
    --sdoc-dir=~/sdoc --ruby-dir=~/ruby --rails-dir=~/rails \\
    --ruby-versions=1.9.3p484 2.0.0p353 2.1.0               \\
    --rails-versions=3.0.20 3.1.12 3.2.16 4.0.2 4.1.0.beta1
LONGDESC
def generate(output_dir)
  ...
end
```

Executing `ruby-rails-documentations help generate` I want my output to be like this:

``` sh
Examples:

bin/ruby-rails-documentations                             \
  generate ~/ruby-rails-documentations                    \
  --sdoc-dir=~/sdoc --ruby-dir=~/ruby --rails-dir=~/rails \
  --ruby-versions=1.9.3p484 2.0.0p353 2.1.0               \
  --rails-versions=3.0.20 3.1.12 3.2.16 4.0.2 4.1.0.beta1
```

Instead, I get this:

``` sh
Examples:

bin/ruby-rails-documentations \
 generate ~/ruby-rails-documentations \
 --sdoc-dir=~/sdoc --ruby-dir=~/ruby --rails-dir=~/rails \
 --ruby-versions=1.9.3p484 2.0.0p353 2.1.0 \
 --rails-versions=3.0.20 3.1.12 
3.2.16 4.0.2 4.1.0.beta1
```

The merged spaces is not a big problem, but the added newlines is - they break the command syntax, and I can't predict where they will be.

Is there any way to force keeping spaces and, above all, force to not break lines?

**Comment by jinhianlee** [comment]
+1 for @bradland's comment.

**Comment by ImaginateWayne** [comment]
Is this change ever getting merged into master?

**Comment by hfossli** [comment]
Bump

**Comment by jsuwo** [comment]
+1

**Comment by vigo** [comment]
+1

**Comment by meissadia** [comment]
\+1

Finding it impossible to get my long_desc displayed correctly. Line-wraps are sporadic once I use \x5.

For my sanity, I've simply redefined Basic#print_wrapped in my project to output the long_desc as-is.
```
class Thor
  module Shell
    class Basic
      def print_wrapped(message, options = {})
         stdout.puts message
       end
    end
  end
end
```

**Comment by aks** [comment]
I like an _option_ to `long_desc`, that disables the wrapping.  eg:

```
long_desc <<~MSG, wrapping: false
  formatted text that is not wrapped
 ...
MSG
```

**Comment by jutonz** [comment]
fwiw you can insert tabs with `\t` until there's a better option available

**Comment by vicmunoz** [comment]
+1

**Comment by sonjz** [comment]
+1

**Comment by djhoffman-stripe** [comment]
+1

**Comment by artob** [comment]
> +1
> 
> Finding it impossible to get my long_desc displayed correctly. Line-wraps are sporadic once I use \x5.
> 
> For my sanity, I've simply redefined Basic#print_wrapped in my project to output the long_desc as-is.
> 
> ```
> class Thor
>   module Shell
>     class Basic
>       def print_wrapped(message, options = {})
>          stdout.puts message
>        end
>     end
>   end
> end
> ```

Thanks for that, @meissadia. Though it was a little too simplistic for me, given a need for indented multi-line output, so I expanded on it slightly:

    # Fix for https://github.com/erikhuda/thor/issues/398
    class Thor::Shell::Basic
      def print_wrapped(message, options = {})
        indent = (options[:indent] || 0).to_i
        if indent.zero?
          self.stdout.puts message
        else
          message.each_line do |message_line|
            self.stdout.print ' ' * indent
            self.stdout.puts message_line.chomp
          end
        end
      end
    end # Thor::Shell::Basic

**Comment by doudou** [comment]
+1
