### ISSUE TITLE
Why treat --force differently?

### ISSUE THREAD

**Issue by Silex** [erikhuda/thor#410]
Hello,

At https://github.com/erikhuda/thor/blob/master/lib/thor/parser/option.rb#L89, you can see that the `--force` option doens't have its `--no-force` option generated.
1. Why treat it differently?
2. How can I achieve the same behavior? I don't want these `--no-foo` aliases.

**Comment by ddarbyson** [comment]
@webdestroya I agree, has this been fixed at all? I would like to only use `--myoption` without the inverted `--no-pretend` option

**Comment by rafaelfranca** [comment]
Force is an internal option and you can't inverse it with a `--no-` option and this is why it is treaded differently. We will track #417 for disabling this feature for users options.
