### ISSUE TITLE
Error when parsing --no-foo with remaining arguments

### ISSUE THREAD

**Issue by michaelmior** [erikhuda/thor#472]
Parsing `--no-foo` seems to erroneously set the option to true if there's some other value after it. I added [a test](https://github.com/michaelmior/thor/blob/no-parse-fail/spec/parser/options_spec.rb#L350) which I think demonstrates this behaviour. Output from the test is given below.

```
Failures:

  1) Thor::Options#parse with :boolean type doesn't eat the next part of the param when negated
     Failure/Error: expect(parse("--no-foo", "bar")).to eq("foo" => false)

       expected: {"foo"=>false}
            got: {"foo"=>true}

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -"foo" => false,
       +"foo" => true,

     # ./spec/parser/options_spec.rb:352:in `block (4 levels) in <top (required)>'
```

**Comment by michaelmior** [comment]
Just some minor additional info. This only seems to happen when `--no-foo` is the last option and there are arguments provided to the command.

**Comment by michaelmior** [comment]
The problem seems to be that `current_is_value?` returns true in `parse_boolean`. It seems to me that `--no-` options should simply not accept values. Something like `--no-foo=true` just doesn't make sense and `--no-foo=false` is unnecessary.

**Comment by doudou** [comment]
Just hit the exact same problem. thor 0.19.1
