### ISSUE TITLE
Print version info

### ISSUE THREAD

**Issue by lebogan** [erikhuda/thor#486]
Can Thor print version info? How? I think I have tried everything I can and google isn't helping.

Thanks for the great gem:-)

**Comment by lebogan** [comment]
I found a way around this delima of mine. May I enter this as a  feature request?

Thank you.

**Comment by astratto** [comment]
@lebogan can you please elaborate a bit on this?

Are you talking about providing a --version to your application?

If so, you can just add a version command and then map --version.

```
    map %w[--version -v] => :version

    desc 'version', 'Show version.'
    def version
      ...my version here from MyGem::VERSION/whatever...
    end
```

**Comment by lebogan** [comment]
I was looking for a way for my apps to print version info and also show "--version -v" as a option when "--help" is requested. After a lot of searching, I came up with this inelegant solution:
  1. Build a throwaway class option for command-line documentation  
```
	class_option :version, :type => :boolean,  :desc => "Show version information"
```
  2. Catch the option as an argument in the main program:  
```
    if ARGV[0] == "--version"  
	  puts "ip_calc version #{IpCalc::VERSION}"  
	  exit 0  
    end  
```
Like I said, not very elegant. It works but shows a "--no-version" on the help screen. I was looking for a builtin function with Thor.

I will try your suggestion. Thank you very much for the response.

Lewis

**Comment by lebogan** [comment]
That works, it's clean. Thank you again for the response. I'm closing
this issue.

**Comment by astratto** [comment]
@lebogan cool!

By the way, I still see this as open.. :question:
