### ISSUE TITLE
Thor Truck Factor

### ISSUE THREAD

**Issue by gavelino** [erikhuda/thor#495]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Thor** and obtained a value of **1**.

The developer responsible for this TF is:

Jose Valim - author of 72% of the files 

To validate our results, we would like to ask **Thor** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Thor**?

(b) Do you agree that **Thor** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Thor** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

**Comment by maxmeyer** [comment]
Did you notice, that his last contributions are from 2013? Really active is only @sferik

**Comment by gavelino** [comment]
Hi Maxmeyer,

We had noticed that, but our heuristic consider all the development history.

**Comment by sferik** [comment]
@gavelino You might want to reconsider your heuristic. To answer your questions:

> (a) Do you agree that the listed developer is the main developer of Thor?

No.

> (b) Do you agree that Thor will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

No.

> (c) Does Thor have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

He is no longer active (i.e. this project has already lost him).
