### ISSUE TITLE
Fetch not working as expected

### ISSUE THREAD

**Issue by codehugger** [erikhuda/thor#504]
Thor::CoreExt::HasWithIndifferentAccess raises KeyError Exception when accessing a hash using a symbol key but returns a value when a string key is used. I am using version (0.19.1) of Thor.

``` ruby
(byebug) h = Thor::CoreExt::HashWithIndifferentAccess.new({"foo" => "bar"})
{"foo"=>"bar"}
(byebug) h.fetch(:foo)
*** KeyError Exception: key not found: :foo


(byebug) h.fetch("foo")
bar
```

If it is any help the bug is not present in ActiveSupport's HashWithIndifferentAccess

```
(byebug) require 'active_support/all'
false
(byebug) ActiveSupport::HashWithIndifferentAccess.new({"foo" => "bar"})
{"foo"=>"bar"}
(byebug) h = ActiveSupport::HashWithIndifferentAccess.new({"foo" => "bar"})
{"foo"=>"bar"}
(byebug) h.fetch(:foo)
bar
(byebug) h.fetch("foo")
bar
```

**Comment by ioquatix** [comment]
This is being monkey-patched by https://github.com/guard/guard/pull/853

Any chance of fixing this?

**Comment by rafaelfranca** [comment]
Could you open a PR?
