### ISSUE TITLE
error when hyphen in an option

### ISSUE THREAD

**Issue by colmac3** [erikhuda/thor#525]
when using an option with a hyphen an error is created.
Example
require 'thor'

class BootParse < Thor

        desc 'chef_node_bootstrap [params]', 'create a node(instance) on aws cloud'
        option :help
        option :node,         :required => true
        option :env,           :required => true
        option :role,           :required => true
        option :bootstrap-only, :type => :boolean

        def create
          node_name =     options['node']
          env =           options['env']
          role =          options['role']
          instance_only = options['instance-only']   # this is true false
        end

end
BootParse.start(ARGV)

Error:
t.error:10:in `<class:BootParse>': undefined local variable or method `only' for BootParse:Class (NameError)
       	from t.error:3:in `<main>'

**Comment by kddeisz** [comment]
`:bootstrap-only` is not a valid ruby symbol, so you're actually hitting what is effectively a ruby parse error. Changing it to `:bootstrap_only` should fix the issue. You can verify by running `ruby <yourscript> help create`.

**Comment by colmac3** [comment]
Thanks for your time. It is all good now :)
