### ISSUE TITLE
New version (0.19.2) is breaking Heroku deploy

### ISSUE THREAD

**Issue by kapso** [erikhuda/thor#533]
```
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:130:in `validate_default_type!'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:113:in `validate!'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/thor-0.19.2/lib/thor/parser/argument.rb:24:in `initialize'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:9:in `initialize'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `new'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `build_option'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:278:in `class_option'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/generators/base.rb:202:in `class_option'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/generators/base.rb:178:in `block in hook_for'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/generators/base.rb:168:in `each'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/generators/base.rb:168:in `hook_for'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/generators/rails/controller/controller_generator.rb:21:in `<class:ControllerGenerator>'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/generators/rails/controller/controller_generator.rb:3:in `<module:Generators>'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/generators/rails/controller/controller_generator.rb:2:in `<module:Rails>'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/generators/rails/controller/controller_generator.rb:1:in `<top (required)>'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_52702d508d5133b16db222d60f6a5f94/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_52702d508d5133b16db222
```

**Comment by excid3** [comment]
Same here. Reverting to 0.19.1 fixes it, so it's definitely introduced in the latest release (0.19.2).

**Comment by reillysiemens** [comment]
This appears to also be breaking `middleman`.
```
[14:22:30] tucker@khanti:/tmp/foo $ middleman init foo
/home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:130:in `validate_default_type!': An option's default must match its type. (ArgumentError)
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:113:in `validate!'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/argument.rb:24:in `initialize'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:9:in `initialize'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `new'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `build_option'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:278:in `class_option'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.12/lib/middleman-cli/server.rb:19:in `<class:Server>'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.12/lib/middleman-cli/server.rb:4:in `<module:Cli>'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.12/lib/middleman-cli/server.rb:2:in `<top (required)>'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/tucker/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.12/bin/middleman:66:in `<top (required)>'
        from /home/tucker/.rbenv/versions/2.3.3/bin/middleman:22:in `load'
        from /home/tucker/.rbenv/versions/2.3.3/bin/middleman:22:in `<main>'
```

**Comment by robdimarco** [comment]
I stumbled across this generating migrations with Rails 5.0.0.1. It looks to be a backwards compatibility issue. Previously, you could have code like:

```
class_option name: 'jbuilder', type: :string, default: true
```
The issue seems related to the code checked in with commit 99bf6863f933f01ac34550bdf441a7511845d9cc
where the string type does not match the default. Previously, this worked just fine, but this commit causes the failure seen.

Perhaps a warning rather than raising an exception would be better?

**Comment by piotrmurach** [comment]
I think it would be good to revert back tests on jruby from this commit https://github.com/erikhuda/thor/commit/264d87c2ebec7ff46fe9cbeab27fd16b0abfbc1d given this problem?

**Comment by mbigras** [comment]
@robdimarco is this related? Using the rails cli is seems to be broken also after a fresh `rails new`, downgrading to `0.19.1` seems to fix it:

    ➜  ~/D/w/t/foobar  ls
    Gemfile      README.md    app          config       db           log          test         vendor
    Gemfile.lock Rakefile     bin          config.ru    lib          public       tmp
    ➜  ~/D/w/t/foobar  bin/rails generate controller SomeController
    Running via Spring preloader in process 89046
    /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:130:in `validate_default_type!': An option's default must match its type. (ArgumentError)
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:113:in `validate!'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/argument.rb:24:in `initialize'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:9:in `initialize'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `new'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `build_option'


      8 # Use Puma as the app server
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:278:in `class_option'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/generators/base.rb:202:in `class_option'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/generators/base.rb:178:in `block in hook_for'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/generators/base.rb:168:in `each'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/generators/base.rb:168:in `hook_for'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jbuilder-2.6.0/lib/generators/rails/scaffold_controller_generator.rb:9:in `<class:ScaffoldControllerGenerator>'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jbuilder-2.6.0/lib/generators/rails/scaffold_controller_generator.rb:6:in `<module:Generators>'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jbuilder-2.6.0/lib/generators/rails/scaffold_controller_generator.rb:5:in `<module:Rails>'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jbuilder-2.6.0/lib/generators/rails/scaffold_controller_generator.rb:4:in `<top (required)>'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jbuilder-2.6.0/lib/jbuilder/railtie.rb:32:in `block in <class:Railtie>'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:230:in `block in run_generators_blocks'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:247:in `each'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:247:in `each_registered_block'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:230:in `run_generators_blocks'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:453:in `block in run_generators_blocks'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine/railties.rb:13:in `each'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine/railties.rb:13:in `each'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:453:in `run_generators_blocks'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:465:in `load_generators'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:144:in `generate_or_destroy'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:60:in `generate'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
      from /Users/max/Dropbox/work/tmp/foobar/bin/rails:9:in `<top (required)>'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      from /Users/max/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      from -e:1:in `<main>'
    ➜  ~/D/w/t/foobar  vim Gemfile
    ➜  ~/D/w/t/foobar  cat Gemfile | grep thor
      gem 'thor', '0.19.1'
    ➜  ~/D/w/t/foobar  rm Gemfile.lock
    ➜  ~/D/w/t/foobar  bundle install
    Using rake 11.3.0
    Using concurrent-ruby 1.0.2
    Using i18n 0.7.0
    .
    .
    .
    Bundle complete! 16 Gemfile dependencies, 62 gems now installed.
    Use `bundle show [gemname]` to see where a bundled gem is installed.
    ➜  ~/D/w/t/foobar  bin/rails generate controller SomeController
    Running via Spring preloader in process 89354
          create  app/controllers/some_controller_controller.rb
    .
    .
    .

**Comment by robdimarco** [comment]
Yes @mbigras it is the same issue.

**Comment by qx** [comment]
0.19.2 broken rails

**Comment by brewster1134** [comment]
breaking when i run rspec via guard as well

```shell
`validate_default_type!': An option's default must match its type. (ArgumentError)
```

**Comment by welkie** [comment]
This breaks generators for latest Rails (currently 5.0.0.1) for me, and also breaks even just using "rails new" for older versions.

```
mwelke@mlap:~$ rails _4.2.4_ new old_app
/var/lib/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:130:in `validate_default_type!': An option's default must match its type. (ArgumentError)
	from /var/lib/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:113:in `validate!'
	from /var/lib/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/argument.rb:24:in `initialize'
	from /var/lib/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:9:in `initialize'
	from /var/lib/gems/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `new'
	from /var/lib/gems/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:544:in `build_option'
	from /var/lib/gems/2.3.0/gems/thor-0.19.2/lib/thor/base.rb:278:in `class_option'
	from /var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/generators/base.rb:202:in `class_option'
	from /var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/generators/app_base.rb:71:in `add_shared_options_for'
	from /var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/generators/rails/app/app_generator.rb:160:in `<class:AppGenerator>'
	from /var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/generators/rails/app/app_generator.rb:159:in `<module:Generators>'
	from /var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/generators/rails/app/app_generator.rb:153:in `<module:Rails>'
	from /var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/generators/rails/app/app_generator.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/commands/application.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/cli.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/railties-4.2.4/bin/rails:9:in `<top (required)>'
	from /usr/local/bin/rails:23:in `load'
	from /usr/local/bin/rails:23:in `<main>'
```

**Comment by sferik** [comment]
I’m going to change 99bf6863f933f01ac34550bdf441a7511845d9cc to output a warning instead of an error and push a new release. Sorry for the trouble.
