### ISSUE TITLE
"run" is a Thor reserved word and cannot be defined as command (RuntimeError)

### ISSUE THREAD

**Issue by ThomasConnolly** [erikhuda/thor#534]
Had to move back to 0.19.1 to run foreman

**Comment by dpandoffx** [comment]
+1

**Comment by juno** [comment]
See https://github.com/ddollar/foreman/issues/655#issuecomment-263188152

**Comment by sferik** [comment]
I did not intend to make a breaking change by renaming is_thor_reserved_word?.

I will change it back and release 0.19.4.

**Comment by Antronin** [comment]
It should not be a breaking change if foreman should use a different word instead of "run". It is a reserved word, and in the above mentioned comment they state it: this is a "hackery". I'm not sure if Thor should adapt t this instead of Foreman.

**Comment by Antronin** [comment]
Also there is a fix in foreman already for this: https://github.com/ddollar/foreman/pull/654
