### ISSUE TITLE
Rails generating error after gem update

### ISSUE THREAD

**Issue by HFR1994** [erikhuda/thor#538]
Between the update from Thor 0.19.1 to Thor 0.19.4 rails commands started generating this warnings:

Running via Spring preloader in process 23121
Expected string default value for '--jbuilder'; got true (boolean)
Expected string default value for '--helper'; got true (boolean)
Expected string default value for '--assets'; got true (boolean)

A quick fix is downgrading Thor to 0.19.1 (both 0.19.2 and 0.19.3 won't get the job done)

Here are my specs:

Rails version:              5.0.1
Ruby version:               2.3.1-p112 (x86_64-linux)
RubyGems version:           2.5.1
Rack version:               2.0.1
JavaScript Runtime:         Node.js (V8)

Thanks

**Comment by trusche** [comment]
See also [this SO question](http://stackoverflow.com/questions/40986923/meaning-of-expected-string-default-value-for-on-ruby-on-rails/41035588#41035588) in case it helps.

**Comment by shadowbq** [comment]
# TODO: This should raise an ArgumentError in a future version of Thor
      warn "Expected #{@type} default value for '#{switch_name}'; got #{@default.inspect} (#{default_type})" unless default_type == @type

**Comment by gltarsa** [comment]
In light of the snippet comment in @shadowbq's note, above, is this actually a problem in `thor` or its caller?

**Comment by SuperTux88** [comment]
The problem with this message is: As a user you don't know where this message comes from, and if it is your fault. And it probably also would be good to see that this is only a warning and nothing is actually broken.

We downgraded thor (we use thor as a dependency of our dependencies) because the message could be confusing for our users.

**Comment by jcoyne** [comment]
As evidence to back up @SuperTux88's claims, see rails/rails#27229, rails/rails#27415, rails/rails#27256.

**Comment by shadowbq** [comment]
this affects other products beyond rails https://github.com/technicalpickles/homesick/issues/156
```
Expected string default value for '--force'; got false (boolean)
```

**Comment by shadowbq** [comment]
this is mostly observed as string input on cli vs boolean setting in a missing/default argument

**Comment by shadowbq** [comment]
this warning is more annoying as when there is no 'type: defined' for the option it defaults to string. Why warn on implicit type casting? enforce explicit or warn on implicit casting.. warning on mismatch of an implicit is misleading.

**Comment by HFR1994** [comment]
Sorry got a little lost, so it's actually making and explicit casting from boolean to string in this case? @shadowbq

**Comment by shadowbq** [comment]
@HFR1994 yes. I don't know which gem, but something is missing 

```ruby
method_option :jbuilder,
type: :boolean,
etc...
```

very likely it's dynamically building that call, but the gist is that you need to static type options for thor using the `method_option`. You could inject pry bindings/or switch it a raise on this warn and trace what gem made the call and make a  patch for that gem.

**Comment by shadowbq** [comment]
Yeah this is all downstream off of https://github.com/rails/rails/blob/v5.0.1/railties/lib/rails/generators/base.rb

https://github.com/rails/jbuilder/issues/371
thor https://github.com/erikhuda/thor/issues/533

**Comment by 5minpause** [comment]
This all seems correct, but I can't find a solution to get rid of the warnings, beside downgrading thor to `0.19.1`.

Is there anything planned to change this or does thor expect their users to change the source of the reported mismatches in their code?

**Comment by rafaelfranca** [comment]
It is expected to the direct users of thor (rails, jbuilder) to fix the warnings. Make sure you are using the latest version of the gems and if the warnings are still there report to the projects.

**Comment by SuperTux88** [comment]
Then please make clear that this are only warnings and where they come from. For the end users it's difficult to detect where these "errors" come from and it's and confusing what they did wrong...

**Comment by rafaelfranca** [comment]
I made clear that the message is a waring at db16e19, but unfortunately there is no way to tell from where they are coming.

**Comment by SuperTux88** [comment]
Thanks, that's already much better 👍

**Comment by mdavidn** [comment]
Just chiming in to say I wasted 15 minutes digging into this warning after my IDE, RubyMine, started displaying these warnings in a popup. For Rails projects, it runs `bin/rails` as part of a built-in (and not obviously configurable) background indexing task. I'm downgrading my projects to 0.19.1.

![screen shot 2017-03-30 at 1 29 09 pm](https://cloud.githubusercontent.com/assets/1015230/24524922/35662cf6-154d-11e7-8095-4bd72b6a5274.png)

**Comment by olivierlacan** [comment]
@rafaelfranca Do you mind cutting a 0.19.5 release from what's on master right now since your recent changes haven't been released? Thanks. 😃

**Comment by rafaelfranca** [comment]
Sure. I still need to finish some things here before releasing. I'll try to finish them this week.

**Comment by henrik** [comment]
@rafaelfranca Ping. Seems 0.19.4 is still the latest pushed gem.

**Comment by jaredbeck** [comment]
If you downgrade thor (like I did) don't forget to leave a comment for the next person who comes along. :heart: Here's the comment I left in my project:

```
# thor > 0.19.1 prints some warnings to stderr which will require changes
# from rails. We can't make the warnings go away. Once rails fixes these
# warnings, this line can be removed entirely from our Gemfile.
# https://github.com/rails/rails/issues/27229
# https://github.com/erikhuda/thor/issues/538
gem 'thor', '0.19.1'
```

**Comment by scifisamurai** [comment]
Just an FYI for anyone else experiencing this issue - upgrading to the current version (0.20.0) of Thor via `bundle update thor` does make these errors go away :).  

https://github.com/erikhuda/thor/blob/v0.20.0/CHANGELOG.md

**Comment by henrik** [comment]
If `bundle update thor` doesn't update it, foreman may be the culprit: https://github.com/ddollar/foreman/issues/688
