### ISSUE TITLE
Weird Hash Behavior

### ISSUE THREAD

**Issue by phene** [erikhuda/thor#543]
```ruby
# With ActiveSupport::HashWithIndifferentAccess
ActiveSupport::HashWithIndifferentAccess.new({ 'foo' => true }).slice(:foo).reverse_merge!(:foo => false)
#=> {"foo"=>true}

# With Thor's HashWithIndifferentAccess
Thor::CoreExt::HashWithIndifferentAccess.new({ 'foo' => true }).slice(:foo).reverse_merge!(:foo => false)
#=> {"foo"=>false}
```

**Comment by rafaelfranca** [comment]
Can you explain why you are using `Thor::CoreExt::HashWithIndifferentAccess`? It is an internal class and should not be used directly by users.

**Comment by phene** [comment]
Because that's what the `options` hash is constructed from. When I want to modify it (with `#slice`) and pass it into my own libraries that provide their own default options (with `#reverse_merge!`), it gets corrupted.

**Comment by rafaelfranca** [comment]
Thanks! Yeah, we should fix it
