### ISSUE TITLE
get current directory~

### ISSUE THREAD

**Issue by gugakatsi** [erikhuda/thor#546]
Sorry maybe it's kinda off topic, i about to integrate thor with my gem and i have this question , i wanna achieve this, whenever user executes my gem from terminal , i wanna get directory where terminal is opened . thanks in advance, sorry for bothering u with silly questions.

**Comment by wstaples** [comment]
I'm not sure what your code looks like but you could try `Dir.pwd`

**Comment by gugakatsi** [comment]
I already solved the issue , but thanks for attention and answer , i will close this issue.
