### ISSUE TITLE
Unspecified/arbitrary options/flags

### ISSUE THREAD

**Issue by AlexEvanczuk** [erikhuda/thor#548]
Does Thor support having arbitrary flags?  I am building a utility that wraps around several other executables, and I want to take in an arbitrary number of flags that come from the other utility and pass them to the next utility without needing to define them explicitly.  I wasn't able to find any examples of this in the wiki.

**Comment by piotrmurach** [comment]
Please don't take it the wrong way but questions like this probably get quicker and better answer at stackoverflow or similar. I'm not entirely sure what you mean either. If you define a command in thor you can define as many flags as you wish and then running the executable it will slurp up anything that it can parse. I think code example of what you're trying to do would improve your chances.

**Comment by rzane** [comment]
I think what @AlexEvanczuk is asking is, how does one accept options that haven't been declared using `method_option`?

For example:

```ruby
# my_cli.rb
require 'thor'

class MyCLI < Thor
  def start(options = {})
  end
end

MyCLI.start
```

```sh
$ ruby my_cli.rb start --foo bar
ERROR: "my_cli.rb start" was called with arguments ["--foo", "bar"]
Usage: "my_cli.rb start"
```

This can be really useful for passing arguments to other shell programs.

**Comment by AlexEvanczuk** [comment]
Hi -- my apologies for not providing a clearer explanation of what I was looking for.  @rzane is exactly right -- I'm looking for a way to pass arguments to other shell programs.  Imagine a hypothetical command line tool (not what I was building but a simple example) where I was wrapping several package managers, allows for some global behavior flagging, and I wanted to customize individual behaviors, e.g.

`$ package_manager bundle yarn --dev brew  --do-a-brew-thing`

I found an easy solution to this was just pass the sub arguments as a string value to a flag rather than a subcommand, and then parse it in my program, e.g. `$ package_manager --bundle --yarn='--dev' --brew='--do-a-brew-thing'`

Still not the best solution (would rather have something that looks a little bit like running the native shell program), but it works.

**Comment by rzane** [comment]
Yeah, another solution is to just splat the args and process them yourself, because splats work fine.

I'm sure there's some method in Thor that converts `['--foo', 'bar']` into `{ foo: 'bar' }`, but I didn't really dig in and try to find that.
