### ISSUE TITLE
Environment variables support

### ISSUE THREAD

**Issue by sliranc** [erikhuda/thor#570]
Support Environment variables as a replacement for options.

Clamp will check the specified envariables in the absence of values supplied on the command line, before looking for a default value.

**Comment by rafaelfranca** [comment]
Can't you already do that by using the environment variable as the default value?

**Comment by sliranc** [comment]
@rafaelfranca working 10x.

**Comment by BobVanB** [comment]
I would like to reopen this.
If the default is used, you provide a way to read the environment variable. This will be shown inside the help.
Enoying if you want default passwords to pass.
