### ISSUE TITLE
0.19.4: instance variable @hide not initialized

### ISSUE THREAD

**Issue by lloeki** [erikhuda/thor#573]
We're cracking down on ruby warnings over here and found this:

```
/Users/lloeki/.gem/ruby/2.3.4/gems/thor-0.19.4/lib/thor.rb:396: warning: instance variable @hide not initialized
```

Seems this is fixed by: https://github.com/erikhuda/thor/pull/562

[Last release](https://rubygems.org/gems/thor/versions) was on November 28, 2016. Any plan for a new release?

**Comment by rafaelfranca** [comment]
Yes. Soon!
