### ISSUE TITLE
Question: record execution time

### ISSUE THREAD

**Issue by eredi93** [erikhuda/thor#577]
I wanna record a metric for the execution time of a Thor CLI command.
Is there a method i can monkey patch?is the `dispatch` method the best method i can use?

would this give me the correct execution time?
```
def dispatch(meth, given_args, given_opts, config)
  with_record_metric(meth) do
    super
  end
end 
```

**Comment by rafaelfranca** [comment]
`invoke` would be the public API for that https://github.com/erikhuda/thor/blob/9dde9502be1730d59eafe2a2e8b3361cb11e3bb7/lib/thor/invocation.rb#L101
