### ISSUE TITLE
boolean options changed in v0.20.0

### ISSUE THREAD

**Issue by toepokesoftware** [erikhuda/thor#580]
I think I have found a possible bug in boolean options.  The value of the option is different when a CLI argument is included.

```ruby
        desc 'test1', 'This is test1 CLI'
        option :skip_upload, default: false, type: :boolean
        def test1
          puts "test1: skip=#{options[:skip_upload]}"
        end

        desc 'test2', 'This is the test2 CLI'
        option :skip_upload, default: false, type: :boolean
        def test2(param)
          puts "test2: skip=#{options[:skip_upload]}"
        end
```

```
$ bundle exec exe/astcli cdr test1
test1: skip=false
$ bundle exec exe/astcli cdr test2 argument
test2: skip=false

$ bundle exec exe/astcli cdr test1 --skip-upload
test1: skip=true
$ bundle exec exe/astcli cdr test2 --skip-upload argument
test2: skip=false
```

**Comment by toepokesoftware** [comment]
Note that the above issue occurs in Thor 0.20.0.  I didn't experience this issue in 0.19.4.

```
##### Thor 0.19.4
$ bundle exec exe/astcli cdr test1 
test1: skip=false
$ bundle exec exe/astcli cdr test2 arg
test2: skip=false
$ bundle exec exe/astcli cdr test1 --skip-upload
test1: skip=true
$ bundle exec exe/astcli cdr test2 --skip-upload arg
test2: skip=true



```

**Comment by rafaelfranca** [comment]
This was a bug fix for erikhuda/thor#472 made in https://github.com/erikhuda/thor/pull/575.

**Comment by doudou** [comment]
> This was a bug fix for erikhuda/thor#472 made in #575.

Well ... it seems that fixing the negative options broke the positive ones. I'm experiencing the exact same problem.

**Comment by rafaelfranca** [comment]
Unfortunately it is already released. We can try to fix forward but I don't think we can revert it.

**Comment by doudou** [comment]
> We can try to fix forward but I don't think we can revert it.

Well ... bugs of course do happen. We're reporting it because otherwise it won't get fixed ;-)

Anyways, thanks to the whole thor team for your work...
