### ISSUE TITLE
Dry run support?

### ISSUE THREAD

**Issue by john-goldsmith** [erikhuda/thor#607]
[🌈](https://github.com/erikhuda/thor/blob/master/CONTRIBUTING.md)

Hi!  I was wondering if dry run support exists such that the textual output/feedback from the `directory` method is yielded without _actually_ producing the files.  For example, my CLI accepts a number of options and can produce quite a few files, so I'd like to provide consumers of my CLI the ability to see exactly how their configuration _will_ look and what files _would_ be produced so they're not burdened with having to manually "undo".  If this isn't supported, perhaps someone can point me to a clever solution of overriding the method, etc.  Thanks!

For clarity, here's an example of Thor's output that I'm referring to:

```sh
exist
create  src/actions/users.js
append  src/types/index.js

# etc.
```

**Comment by rafaelfranca** [comment]
Yes. It is the `pretend` option. You can find it by running `your_command --help`

**Comment by john-goldsmith** [comment]
Worked like a charm, thanks!  For anyone who might stumble across this in the future:

```ruby
class MyGenerator < Thor::Group
  include Thor::Actions
  add_runtime_options!
end
```
