### ISSUE TITLE
Namespace Classes Specific to Thor Gem

### ISSUE THREAD

**Issue by Diasporism** [erikhuda/thor#615]
Hey, first of all thanks for the work behind this gem.

I'm running into a namespace collision with Thor, specifically with the `Color` module. We've had a class named Color in our app for years, but a required dependency bump forced us from version 0.14 (2010!) to 0.19.

Unfortunately, now Rails is telling me Color is not a class when I try to boot our server and it dies. Perusing the load path I discovered it's a module defined here in Thor.

Faker is another gem that uses quite a few generic class and module names, but everything is namespaced (example: `Faker::Email`) so there are no collisions.

Any chance the active contributors here could take the same approach? Thor is a sub-dependency of a few gems that would take an enormous amount of work to remove from our app, and while renaming my Color class is something I can do in the mean time, it's not very polite to hoard all the generic nouns for yourself :)

Edit:

For anyone else having issues like this, in the mean time I've added this directly above my conflicting class definition:

```ruby
Object.send(:remove_const, :Color) if defined?(Color) && Color.instance_of?(::Module)

class Color < ActiveRecord::Base
  ...
end
```

But I'm not exactly sure how this will impact gems that are requiring Thor as a dependency in my app.

**Comment by MaxLap** [comment]
I can't find that top level Color module you mention. All I find is Thor::Shell::Color

Could you post a Ruby snippet showing that top-level Color module?
