### ISSUE TITLE
Document check_unknown_options!

### ISSUE THREAD

**Issue by MaxLap** [erikhuda/thor#617]
I didn't find where i could do a PR for the whatisthor page. But I think it would be very helpful to mention `check_unknown_options!` somewhere on it (Probably in the first example actually).

I literally discarded thor as an option for my cli because the default behavior is just weird in my mind and I didn't know about `check_unknown_options!`. It is literally spoken of nowhere except in the source code. 

It's in my mind really sad that this isn't the default, but I understand this is about backward compatibility.

I'd be willing to do the PR if the website is open source.

**Comment by rafaelfranca** [comment]
Feel free to open a PR. The site is on the gh-pages branch of this repo https://github.com/erikhuda/thor/tree/gh-pages
