### ISSUE TITLE
global variable `$thor_runner' not initialized

### ISSUE THREAD

**Issue by graywolf-at-work** [erikhuda/thor#633]
I'm getting warning when running my program (which uses Thor) with `$VERBOSE = true`:

    /home/wolf/.rvm/gems/ruby-2.5.3@sm-toolkit/gems/thor-0.20.0/lib/thor.rb:396: warning: global variable `$thor_runner' not initialized

simple repro:

```
#!/usr/bin/ruby

$VERBOSE = true

require 'thor'

class Test < Thor
end

Test.start(ARGV)
```

**Comment by hadmut** [comment]
Still in 0.20.3:

/var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:396: warning: global variable `$thor_runner' not initialized

**Comment by hadmut** [comment]
Any chance to get this fixed?
