### ISSUE TITLE
Thor tries to create command from private method

### ISSUE THREAD

**Issue by graywolf-at-work** [erikhuda/thor#634]
```
[WARNING] Attempted to create command "foo" without usage or description. Call desc if you want this method to be available as command or declare it inside a no_commands{} block. Invoked from "./repro.rb:6:in `<class:Test>'".
```

repro:

```
#!/usr/bin/ruby

require 'thor'

class Test < Thor
  private def foo; end
end
```

**Comment by rafaelfranca** [comment]
This way of defining private methods can't work with thor. It uses `method_added` hooks and when the method is defined it is public, so we think the method will be public and show a warning.

If you want to use this form of definition you need to put it inside a `no_commands` block.

**Comment by graywolf-at-work** [comment]
than not much to do about this :) Thanks for quick answer
