### ISSUE TITLE
options.to_hash returns string keys instead of symbol keys

### ISSUE THREAD

**Issue by hadmut** [erikhuda/thor#658]
Hi, 
when thor calls a method, it passes the option in an option variable of type Thor::CoreExt::HashWithIndifferentAccess

There is a function to_hash, which converts this into a regular hash, but the keys of this hash (i.e. the option names) are strings now, instead of symbols as in  option[:name]

disadvantage: It it was symbols, one could directly pass the options as named parameters as in 

somefunction(name: name, **options)

**Comment by rafaelfranca** [comment]
The behavior of `to_hash` is the intended. `HashWithIndifferentAccess` store the keys as strings so if you convert it to a Hash it will have string keys.
