### ISSUE TITLE
Do the action outside of the `Thor` instance

### ISSUE THREAD

**Issue by paul-mesnilgrente** [erikhuda/thor#685]
I started to use the Thor gem thinking I could have it behaving like `OptionParser`. But I am struggling on 1 point. With `OptionParser`, you can define an object like `options = {}` and modify it in the block.

I don't find any way to get an object out of my `ArgumentParser`. In clear: I don't want to do my actions in the `ArgumentParser`.

```
#!/usr/bin/env ruby

require 'thor'

class Action
  def initialize(name)
    @name = name
  end
end

class AddAction < Action
  def call
    # do my stuff on the database
    return "Your item has been added"
  end
end

class HelpAction < Action
  def call
    # how do I get and return the help text?
  end
end

class ArgumentParser < Thor
  desc "add NAME"
  def add(name)
    add_a = AddAction.new(name)
    # how do I return add_a to the `ArgumentParser` caller?
  end
end

MyCLI.start(ARGV)
# is there an alternative to `start`?
# I want to get an instance of `Action` instead
```

The reason is that I am using `Thor` in a web server context and I don't want to print logs but return a JSON response depending on the parameters.

**Comment by rafaelfranca** [comment]
Thor is not a argument parser. It is an object to define and execute actions. There is no way to do what you want using Thor.
