### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by deivid-rodriguez** [erikhuda/thor#687]
Next Sunday, it'll be exactly one year since [the last release of thor](https://rubygems.org/gems/thor/versions/0.20.3).

I was wondering if there's plans for a new release?

I tried [rails](https://github.com/rails/rails/pull/37651) and [bundler](https://github.com/rails/rails/pull/37651) against the master branch of `thor`, and things are working fine (from a CI point of view, at least).

Thanks!!

**Comment by rafaelfranca** [comment]
I do have plans to make a new release and I believe it should be the 1.0. I still need to verify if there is any feature I want to include inside thor before doing so. I'll try to do in the next weeks.

**Comment by IrimieBogdan** [comment]
@rafaelfranca  a new release would be great, we need to use the functionality `allows multiple values if repeatable is specified` and it would be great to have it in an official release.

**Comment by rafaelfranca** [comment]
I'm just preparing the release. It will require Rails to be released before thor otherwise we will see a lot of warnings. I'll start the preparation for a Rails release.

**Comment by rafaelfranca** [comment]
1.0.0 released
