### ISSUE TITLE
How to pass option value to task method?

### ISSUE THREAD

**Issue by niksfirefly** [erikhuda/thor#702]
I need to run task multiple times so i cant use invoke.
I found out that I can run task multiple times directly but I don't know how to pass changed options to task.

for example
```

def task(arg)
  puts "Running task with #{arg}"
end

def main_task
  task(arg)
  task(arg)
  task(arg)
end
```
How can i run task in main_task with different options?

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
